"""
routes/topic_quiz_routes.py

GET  /api/topic-quiz/<skill>/<topic>?focusBand=<band> -> 10-question
     quiz (bank first, AI fills any shortfall). Cached per
     (skill, topic, focusBand) — shared across every student in that
     category, generated by AI once and reused after that, including
     on revision retakes. See services/topic_quiz_bank_cache.py.

POST /api/topic-quiz/<skill>/<topic>/submit   -> scores the attempt,
     classifies the learner (Fast/Moderate/Slow), schedules the next
     revision date, and persists both the attempt and updated progress.

GET  /api/topic-quiz/<uid>/progress           -> every topic_quiz_progress
     doc for this learner (each with its own FocusBand + Classification
     from that topic's own quiz results) — read once by the frontend's
     Course Workspace to make content depth per-topic instead of fixed
     at whatever the one-time diagnostic assessed for the whole skill.

GET  /api/revisions/<uid>                     -> { due: [...], upcoming: [...] }
     due = due today or overdue, upcoming = next 7 days — backs the
     Revision page's "Today's Revision" / "Upcoming Revision Sessions".

POST /api/revisions/<uid>/<skill>/<topic>/snooze -> pushes that topic's
     NextReviewDate forward by one day, without requiring a quiz retake.
"""

from flask import Blueprint, request

from services.topic_quiz_service import (
    get_topic_quiz, submit_topic_quiz, get_due_revisions, snooze_topic_revision,
    get_topic_progress, TopicQuizError,
)
from utils.response_helper import success_response, error_response

topic_quiz_bp = Blueprint("topic_quiz", __name__)


@topic_quiz_bp.route("/topic-quiz/<skill>/<topic>", methods=["GET"])
def get_topic_quiz_route(skill, topic):
    focus_band = request.args.get("focusBand")
    if not focus_band:
        return error_response("focusBand query param is required.", status_code=400)
    try:
        quiz = get_topic_quiz(skill=skill, topic=topic, focus_band=focus_band)
        return success_response(data=quiz, message="Topic quiz ready.")
    except TopicQuizError as exc:
        return error_response(str(exc), status_code=422)
    except Exception as exc:  # noqa: BLE001
        return error_response(str(exc), status_code=500)


@topic_quiz_bp.route("/topic-quiz/<skill>/<topic>/submit", methods=["POST"])
def submit_topic_quiz_route(skill, topic):
    payload = request.get_json(silent=True) or {}
    uid = payload.get("uid")
    questions = payload.get("questions")
    answers = payload.get("answers")
    time_taken_seconds = payload.get("timeTakenSeconds", 0)

    if not uid:
        return error_response("uid is required.", status_code=400)
    if not isinstance(questions, list) or not questions:
        return error_response("questions (list, echoed back from the GET response) is required.", status_code=400)
    if not isinstance(answers, dict):
        return error_response("answers (object) is required.", status_code=400)

    try:
        result = submit_topic_quiz(
            uid=uid, skill=skill, topic=topic,
            questions=questions, answers=answers,
            time_taken_seconds=int(time_taken_seconds),
        )
        return success_response(data=result, message="Quiz submitted.")
    except TopicQuizError as exc:
        return error_response(str(exc), status_code=422)
    except Exception as exc:  # noqa: BLE001
        return error_response(str(exc), status_code=500)


@topic_quiz_bp.route("/topic-quiz/<uid>/progress", methods=["GET"])
def get_topic_progress_route(uid):
    try:
        progress = get_topic_progress(uid=uid)
        return success_response(data=progress, message=f"{len(progress)} topic(s) with recorded progress.")
    except Exception as exc:  # noqa: BLE001
        return error_response(str(exc), status_code=500)


@topic_quiz_bp.route("/revisions/<uid>", methods=["GET"])
def get_due_revisions_route(uid):
    try:
        result = get_due_revisions(uid=uid)
        total = len(result["due"]) + len(result["upcoming"])
        return success_response(data=result, message=f"{total} revision(s) found.")
    except Exception as exc:  # noqa: BLE001
        return error_response(str(exc), status_code=500)


@topic_quiz_bp.route("/revisions/<uid>/<skill>/<topic>/snooze", methods=["POST"])
def snooze_revision_route(uid, skill, topic):
    try:
        progress = snooze_topic_revision(uid=uid, skill=skill, topic=topic)
        return success_response(data=progress, message="Revision postponed to tomorrow.")
    except TopicQuizError as exc:
        return error_response(str(exc), status_code=422)
    except Exception as exc:  # noqa: BLE001
        return error_response(str(exc), status_code=500)
