/**
 * Dummy earned-certificates list. Same shape a future
 * GET /api/certificates response would have.
 */
export const CERTIFICATES = [
  {
    id: "cert1",
    title: "Certificate of Completion",
    courseName: "Cybersecurity Foundations",
    careerPath: "Cyber Security Analyst",
    studentName: "Selva Meenakshi K",
    issueDate: "2026-05-05",
    completionDate: "2026-05-02",
    certificateId: "LM-CSF-20260505-1021",
    score: 92,
    status: "Verified",
    issuer: "LearnMatrix",
    mentor: "AI Mentor — Nova",
    skills: ["Network Basics", "Threat Modeling", "Security Fundamentals"],
    thumbnail: null,
    verificationUrl: "https://learnmatrix.app/verify/LM-CSF-20260505-1021",
    downloadUrl: "#",
  },
  {
    id: "cert2",
    title: "Certificate of Completion",
    courseName: "Introduction to Ethical Hacking",
    careerPath: "Cyber Security Analyst",
    studentName: "Selva Meenakshi K",
    issueDate: "2026-06-12",
    completionDate: "2026-06-10",
    certificateId: "LM-IEH-20260612-1021",
    score: 88,
    status: "Verified",
    issuer: "LearnMatrix",
    mentor: "AI Mentor — Nova",
    skills: ["Reconnaissance", "Vulnerability Scanning", "Reporting"],
    thumbnail: null,
    verificationUrl: "https://learnmatrix.app/verify/LM-IEH-20260612-1021",
    downloadUrl: "#",
  },
  {
    id: "cert3",
    title: "Certificate of Completion",
    courseName: "Linux for Security Professionals",
    careerPath: "Cyber Security Analyst",
    studentName: "Selva Meenakshi K",
    issueDate: "2026-06-30",
    completionDate: "2026-06-28",
    certificateId: "LM-LSP-20260630-1021",
    score: 79,
    status: "Pending",
    issuer: "LearnMatrix",
    mentor: "AI Mentor — Nova",
    skills: ["Shell Scripting", "File Permissions", "System Hardening"],
    thumbnail: null,
    verificationUrl: "https://learnmatrix.app/verify/LM-LSP-20260630-1021",
    downloadUrl: "#",
  },
];
