
/**
 * A curated list of well-known Tamil Nadu colleges/universities, shown in
 * the searchable "College" dropdown on the Sign Up form (College Student
 * user type only). "Other / Not Listed" is always appended at the end so
 * nobody is stuck if their college isn't here.
 */
export const TN_COLLEGES = [
  "Anna University, Chennai",
  "College of Engineering Guindy, Chennai",
  "SSN College of Engineering, Chennai",
  "Loyola College, Chennai",
  "Madras Christian College, Chennai",
  "Stella Maris College, Chennai",
  "Presidency College, Chennai",
  "Sathyabama Institute of Science and Technology, Chennai",
  "SRM Institute of Science and Technology, Chennai",
  "Hindustan Institute of Technology and Science, Chennai",
  "Rajalakshmi Engineering College, Chennai",
  "Panimalar Engineering College, Chennai",
  "Velammal Engineering College, Chennai",
  "Vellore Institute of Technology (VIT), Vellore",
  "Thiagarajar College of Engineering, Madurai",
  "Thiagarajar College of Arts and Science, Madurai",
  "American College, Madurai",
  "Fatima College, Madurai",
  "Lady Doak College, Madurai",
  "Madurai Kamaraj University, Madurai",
  "Mepco Schlenk Engineering College, Sivakasi",
  "Kalasalingam Academy of Research and Education, Krishnankoil",
  "PSNA College of Engineering and Technology, Dindigul",
  "PSG College of Technology, Coimbatore",
  "PSG College of Arts and Science, Coimbatore",
  "Coimbatore Institute of Technology",
  "Kumaraguru College of Technology, Coimbatore",
  "Government College of Technology, Coimbatore",
  "Sri Ramakrishna Engineering College, Coimbatore",
  "Karpagam College of Engineering, Coimbatore",
  "Sri Krishna College of Engineering and Technology, Coimbatore",
  "Sri Krishna Arts and Science College, Coimbatore",
  "Bharathiar University, Coimbatore",
  "Bannari Amman Institute of Technology, Sathyamangalam",
  "National Institute of Technology (NIT), Trichy",
  "Bharathidasan University, Trichy",
  "Bishop Heber College, Trichy",
  "St. Joseph's College, Trichy",
  "SASTRA Deemed University, Thanjavur",
  "Annamalai University, Chidambaram",
  "Alagappa University, Karaikudi",
  "Manonmaniam Sundaranar University, Tirunelveli",
  "St. Xavier's College, Palayamkottai",
  "Government College of Engineering, Tirunelveli",
  "Government College of Engineering, Salem",
  "Periyar University, Salem",
  "Vellalar College for Women, Erode",
  "Kongu Engineering College, Erode",
  "Nandha Engineering College, Erode",
  "Other / Not Listed",
];
