"""
firebase/firebase_config.py

Prepares (but does not force) the Firebase Admin SDK connection.

Design decision: the SDK is initialized LAZILY, on first call to
`get_firestore_client()`, not at import time. This means:
  - The whole backend can start and serve dummy JSON right now, even though
    serviceAccountKey.json does not exist yet.
  - Firestore is only touched the moment a service actually calls it.
  - There is exactly one Firebase app instance (guarded by `_initialized`),
    no matter how many services import this module.

No serviceAccountKey.json is generated by this file. Drop your real key at
the path defined in config/settings.py (FIREBASE_SERVICE_ACCOUNT_PATH) when
you're ready to go live.
"""

import os
import firebase_admin
from firebase_admin import credentials, firestore

from config.settings import settings

_initialized = False


def _ensure_initialized() -> None:
    """Initialize the Firebase Admin app exactly once."""
    global _initialized
    if _initialized:
        return

    if not os.path.exists(settings.FIREBASE_SERVICE_ACCOUNT_PATH):
        raise FileNotFoundError(
            "Firebase service account key not found at "
            f"'{settings.FIREBASE_SERVICE_ACCOUNT_PATH}'. "
            "Add serviceAccountKey.json before calling Firestore."
        )

    cred = credentials.Certificate(settings.FIREBASE_SERVICE_ACCOUNT_PATH)
    firebase_admin.initialize_app(cred)
    _initialized = True


def get_firestore_client():
    """
    Return a Firestore client, initializing the Firebase app on first use.

    Every service module (role_service, question_service, etc.) should call
    this instead of importing firebase_admin directly — that keeps Firebase
    plumbing in exactly one file.
    """
    _ensure_initialized()
    return firestore.client()
